### Stage 1: The minimal runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
WORKDIR /work/

# Copy the native executable from the build context
COPY target/*-runner /work/application

# Set permissions and ownership
RUN chown 1001 /work/application \
    && chmod 555 /work/application

EXPOSE 8080
USER 1001
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]