quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:///pedidoscompras
quarkus.datasource.jdbc.url=jdbc:h2:file:./pedidoscompras
quarkus.datasource.username=sa
quarkus.datasource.password=123

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.sql=true

quarkus.jacoco.excludes=com/ada/pedido/Startup.class,com/ada/pedido/Main.class

# Swagger UI & OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
